/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_JniEntity */

#ifndef _Included_com_example_JniEntity
#define _Included_com_example_JniEntity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_JniEntity
 * Method:    fork
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_JniEntity_fork (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
